# Generated by Django 3.1.2 on 2020-11-07 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='votedown',
            field=models.ManyToManyField(blank=True, related_name='votesdowm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='voteup',
            field=models.ManyToManyField(blank=True, related_name='votesup', to=settings.AUTH_USER_MODEL),
        ),
    ]
