# Generated by Django 3.0.4 on 2020-11-09 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20201108_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
