# Generated by Django 3.1.2 on 2020-11-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201106_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='userProfile/default.png', upload_to='userProfile'),
        ),
    ]
